# Generated by Django 6.1 on 2026-08-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_menu_comment_ingredient_recipe_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='menu',
            field=models.ManyToManyField(null=True, to='recipes.menu'),
        ),
    ]
