# Generated by Django 6.1 on 2026-09-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredient_quantity_remove_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
